name: Runtime Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'
  push:
    branches: [master, main, develop]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        go: ['1.14', '1.15']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install tesseract
        run: brew install tesseract
      - name: Install pkg
        run: go get -u -v -t ./...
      - name: Test
        run: go test -v -cover ./...
  windows:
    # https://github.com/charlesw/tesseract/wiki/Compiling-Tesseract-and-Libleptonica-(using-vcpkg)
    # https://stackoverflow.com/questions/50951283/tesseract-install-using-vcpkg-in-windows-10
    # https://stackoverflow.com/questions/50658953/install-tesseract-for-c-on-windows-10/50662383
    runs-on: windows-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Install tesseract for x86
        run: vcpkg install tesseract:x86-windows
      - name: Install tesseract for x64
        run: vcpkg install tesseract:x64-windows
      - name: Test
        run: go test -v -cover ./...
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - ubuntu
          - alpine
          - archlinux
          - centos
          - debian
          - fedora
          - mingw
          - quickstart
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: ${{ matrix.runtime }}
        shell: 'script -q -e -c "bash {0}"'
        run: bash ./test/runtime --driver docker --build --run ${{ matrix.runtime }}
