name: Runtime Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'
  push:
    branches: [master, main, develop]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        go: ['1.14', '1.15']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install tesseract
        run: brew install tesseract
      - name: Install pkg
        run: go get -u -v -t ./...
      - name: Test
        run: go test -v -cover ./...
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - ubuntu
          - alpine
          - archlinux
          - centos
          - debian
          - fedora
          - mingw
          - quickstart
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: ${{ matrix.runtime }}
        shell: 'script -q -e -c "bash {0}"'
        run: bash ./test/runtime --build --run ${{ matrix.runtime }}

  vagrant-test:
    runs-on: macos-10.15
    strategy:
      matrix:
        runtime:
          - freebsd
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: ${{ matrix.runtime }}
        run: bash ./test/runtime --build --run ${{ matrix.runtime }}
