name: Runtime Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'
  push:
    branches: [master, main, develop]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        go: ['1.14', '1.15']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install tesseract
        run: brew install tesseract
      - name: Install pkg
        run: go get -u -v -t ./...
      - name: Test
        run: go test -v -cover ./...
  # https://github.com/charlesw/tesseract/wiki/Compiling-Tesseract-and-Libleptonica-(using-vcpkg)
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: image libs
        run: |
          vcpkg install giflib:x86-windows-static libjpeg-turbo:x86-windows-static liblzma:x86-windows-static libpng:x86-windows-static tiff:x86-windows-static zlib:x86-windows-static
      - name: Leptonica
        run: |
          git clone https://github.com/DanBloomberg/leptonica.git
          cd leptonica
          git checkout -b 1.78.0 1.78.0
          mkdir vs16-x86
          cd vs16-x86
          mkdir ..\..\build\x86
          cmake .. -G "Visual Studio 16 2019" -A Win32 -DCMAKE_TOOLCHAIN_FILE=%VCPKG_HOME%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_INSTALL_PREFIX=..\..\build\x86
          cmake --build . --config Release --target install
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - ubuntu
          - alpine
          - archlinux
          - centos
          - debian
          - fedora
          - mingw
          - quickstart
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: ${{ matrix.runtime }}
        shell: 'script -q -e -c "bash {0}"'
        run: bash ./test/runtime --driver docker --build --run ${{ matrix.runtime }}
